name: ${artifactId}
main: ${mainClass}
version: ${project.version}
author: ${author}
authors: [${authors}]
description: ${project.description}
depend: [${hardDepend}]
softdepend: [${softDepend}]
#################################################################################################
